"""empty message

Revision ID: 83ecc3def9d8
Revises: df66d0c8f60f
Create Date: 2022-08-22 09:55:19.601403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ecc3def9d8'
down_revision = 'df66d0c8f60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('species', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('image', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('created', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('characters', sa.String(length=120), nullable=False),
    sa.Column('locations', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['characters'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['locations'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('characters'),
    sa.UniqueConstraint('characters')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('dimension', sa.Boolean(), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('created', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.add_column('user', sa.Column('favorites', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'user', 'favorites', ['favorites'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'favorites')
    op.drop_table('locations')
    op.drop_table('favorites')
    op.drop_table('characters')
    # ### end Alembic commands ###
